name: yummy
description: "Yummy is a food platform for customers to order food from a wide variety of restaurants"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/food/
    - assets/restaurants/
    - assets/profile_pics/
